defaults: &defaults
  host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  database: rails3_mongoid_devise_development

test:
  <<: *defaults
  database: rails3_mongoid_devise_test

#just like the production site (before moving to u-servers)
staging:
  uri: <%= ENV['MONGOHQ_URL'] %>
  max_retries_on_connection_failure: 20
  persist_in_safe_mode: true
  skip_version_check: true
  #  host: <%= ENV['MONGOID_HOST'] %>
  #  port: <%= ENV['MONGOID_PORT'] %>
  #  username: <%= ENV['MONGOID_USERNAME'] %>
  #  password: <%= ENV['MONGOID_PASSWORD'] %>
  #  database: <%= ENV['MONGOID_DATABASE'] %>
  #  uri: mongodb://hans:hans@alex.mongohq.com:10093/app8798946 || <%= ENV['MONGOHQ_URL'] %>

#just like the production site (before moving to u-servers)
heroku_production:
  uri: <%= ENV['MONGOHQ_URL'] %>
  max_retries_on_connection_failure: 20
  persist_in_safe_mode: true
  skip_version_check: true
  #  host: <%= ENV['MONGOID_HOST'] %>
  #  port: <%= ENV['MONGOID_PORT'] %>
  #  username: <%= ENV['MONGOID_USERNAME'] %>
  #  password: <%= ENV['MONGOID_PASSWORD'] %>
  #  database: <%= ENV['MONGOID_DATABASE'] %>
  #  uri: mongodb://hans:hans@alex.mongohq.com:10093/app8798946 || <%= ENV['MONGOHQ_URL'] %>

# set these environment variables on your prod server
production:
  <<: *defaults
  database: rails3_mongoid_devise_production
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
  #the nexts 4 lines are to connect with the heroku addon
  #uri: <%= ENV['MONGOHQ_URL'] %>
  #max_retries_on_connection_failure: 20
  #persist_in_safe_mode: true
  #skip_version_check: true
  #the next lines dont work correctly
  #  host: <%= ENV['MONGOID_HOST'] %>
  #  port: <%= ENV['MONGOID_PORT'] %>
  #  username: <%= ENV['MONGOID_USERNAME'] %>
  #  password: <%= ENV['MONGOID_PASSWORD'] %>
  #  database: <%= ENV['MONGOID_DATABASE'] %>
  #  uri: mongodb://hans:hans@alex.mongohq.com:10093/app8798946 || <%= ENV['MONGOHQ_URL'] %>